send chobby state whenever a player joins
beyond-all-reason/spads_config_bar pull request #79
Opened 2023-02-15 22:58 UTC by Jazcash

Lobby should be told of all the SPADS settings up front when a player joins a battle

2023-02-20 11:07 UTC, Beherith requested changes
So, while the idea behind this is more than sane, I feel that resending chobby state on every join might be a bit too many messages spam.

also, this callback is for when a player makes it ingame into the running battle, from the autohost, not the lobby side, so this is not the right handler.

2023-02-20 12:14 UTC, Jazcash commented
Does chobby not support hiding messages? Ideally all barmanager messages would be hidden from normal chat.

Didn't realise I had the wrong handler though, I'm not quite sure where the right place is.

https://github.com/beyond-all-reason/spads_config_bar/blob/main/var/plugins/barmanager.py#L765 already has a call to `SendChobbyState()` in it, so I assumed that wasn't the right handler because currently clients joining a battle don't always get the state message.

2023-07-29 07:07 UTC, Beherith commented
Fixed now :)

2023-07-29 07:07 UTC, closed without merging

2023-07-29 21:35 UTC, Jazcash commented
ooo what was the fix?